//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC3_GUI.CretaLanguages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AlarmsPlotter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlarmsPlotter() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CC3_GUI.CretaLanguages.AlarmsPlotter", typeof(AlarmsPlotter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMERGENCY BUTTON PRESSED.
        /// </summary>
        internal static string P_ALARM_001 {
            get {
                return ResourceManager.GetString("P_ALARM_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAFETY BARRIER.
        /// </summary>
        internal static string P_ALARM_002 {
            get {
                return ResourceManager.GetString("P_ALARM_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOTOR X AXIS.
        /// </summary>
        internal static string P_ALARM_003 {
            get {
                return ResourceManager.GetString("P_ALARM_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOTOR Y AXIS.
        /// </summary>
        internal static string P_ALARM_004 {
            get {
                return ResourceManager.GetString("P_ALARM_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOTOR Z AXIS.
        /// </summary>
        internal static string P_ALARM_005 {
            get {
                return ResourceManager.GetString("P_ALARM_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a STIRRER VARIATOR.
        /// </summary>
        internal static string P_ALARM_006 {
            get {
                return ResourceManager.GetString("P_ALARM_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DRIVE BELT MOTOR.
        /// </summary>
        internal static string P_ALARM_007 {
            get {
                return ResourceManager.GetString("P_ALARM_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO AIR IN AIR CIRCUIT (SUCTION).
        /// </summary>
        internal static string P_ALARM_008 {
            get {
                return ResourceManager.GetString("P_ALARM_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AXIS X MOTOR NOT ADJUSTED.
        /// </summary>
        internal static string P_ALARM_009 {
            get {
                return ResourceManager.GetString("P_ALARM_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AXIS Y MOTOR NOT ADJUSTED.
        /// </summary>
        internal static string P_ALARM_010 {
            get {
                return ResourceManager.GetString("P_ALARM_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AXIS Z MOTOR NOT ADJUSTED.
        /// </summary>
        internal static string P_ALARM_011 {
            get {
                return ResourceManager.GetString("P_ALARM_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH X AXIS.
        /// </summary>
        internal static string P_ALARM_012 {
            get {
                return ResourceManager.GetString("P_ALARM_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH Y AXIS.
        /// </summary>
        internal static string P_ALARM_013 {
            get {
                return ResourceManager.GetString("P_ALARM_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH Z AXIS.
        /// </summary>
        internal static string P_ALARM_014 {
            get {
                return ResourceManager.GetString("P_ALARM_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH OTB.
        /// </summary>
        internal static string P_ALARM_015 {
            get {
                return ResourceManager.GetString("P_ALARM_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAILSAFE BAR 1.
        /// </summary>
        internal static string P_ALARM_016 {
            get {
                return ResourceManager.GetString("P_ALARM_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAILSAFE BAR 2.
        /// </summary>
        internal static string P_ALARM_017 {
            get {
                return ResourceManager.GetString("P_ALARM_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAILSAFE BAR 3.
        /// </summary>
        internal static string P_ALARM_018 {
            get {
                return ResourceManager.GetString("P_ALARM_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAILSAFE BAR 4.
        /// </summary>
        internal static string P_ALARM_019 {
            get {
                return ResourceManager.GetString("P_ALARM_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAILSAFE BAR 5.
        /// </summary>
        internal static string P_ALARM_020 {
            get {
                return ResourceManager.GetString("P_ALARM_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAILSAFE BAR 6.
        /// </summary>
        internal static string P_ALARM_021 {
            get {
                return ResourceManager.GetString("P_ALARM_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAILSAFE BAR 7.
        /// </summary>
        internal static string P_ALARM_022 {
            get {
                return ResourceManager.GetString("P_ALARM_022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAILSAFE BAR 8.
        /// </summary>
        internal static string P_ALARM_023 {
            get {
                return ResourceManager.GetString("P_ALARM_023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMPTY RESERVOIR, BAR 1.
        /// </summary>
        internal static string P_ALARM_024 {
            get {
                return ResourceManager.GetString("P_ALARM_024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMPTY RESERVOIR, BAR 2.
        /// </summary>
        internal static string P_ALARM_025 {
            get {
                return ResourceManager.GetString("P_ALARM_025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMPTY RESERVOIR, BAR 3.
        /// </summary>
        internal static string P_ALARM_026 {
            get {
                return ResourceManager.GetString("P_ALARM_026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMPTY RESERVOIR, BAR 4.
        /// </summary>
        internal static string P_ALARM_027 {
            get {
                return ResourceManager.GetString("P_ALARM_027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMPTY RESERVOIR, BAR 5.
        /// </summary>
        internal static string P_ALARM_028 {
            get {
                return ResourceManager.GetString("P_ALARM_028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMPTY RESERVOIR, BAR 6.
        /// </summary>
        internal static string P_ALARM_029 {
            get {
                return ResourceManager.GetString("P_ALARM_029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMPTY RESERVOIR, BAR 7.
        /// </summary>
        internal static string P_ALARM_030 {
            get {
                return ResourceManager.GetString("P_ALARM_030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMPTY RESERVOIR, BAR 8.
        /// </summary>
        internal static string P_ALARM_031 {
            get {
                return ResourceManager.GetString("P_ALARM_031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILL RESERVOIR 1.
        /// </summary>
        internal static string P_ALARM_032 {
            get {
                return ResourceManager.GetString("P_ALARM_032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILL RESERVOIR 2.
        /// </summary>
        internal static string P_ALARM_033 {
            get {
                return ResourceManager.GetString("P_ALARM_033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILL RESERVOIR 3.
        /// </summary>
        internal static string P_ALARM_034 {
            get {
                return ResourceManager.GetString("P_ALARM_034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILL RESERVOIR 4.
        /// </summary>
        internal static string P_ALARM_035 {
            get {
                return ResourceManager.GetString("P_ALARM_035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILL RESERVOIR 5.
        /// </summary>
        internal static string P_ALARM_036 {
            get {
                return ResourceManager.GetString("P_ALARM_036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILL RESERVOIR 6.
        /// </summary>
        internal static string P_ALARM_037 {
            get {
                return ResourceManager.GetString("P_ALARM_037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILL RESERVOIR 7.
        /// </summary>
        internal static string P_ALARM_038 {
            get {
                return ResourceManager.GetString("P_ALARM_038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILL RESERVOIR 8.
        /// </summary>
        internal static string P_ALARM_039 {
            get {
                return ResourceManager.GetString("P_ALARM_039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH INKBOX 1.
        /// </summary>
        internal static string P_ALARM_040 {
            get {
                return ResourceManager.GetString("P_ALARM_040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH INKBOX 2.
        /// </summary>
        internal static string P_ALARM_041 {
            get {
                return ResourceManager.GetString("P_ALARM_041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH INKBOX 3.
        /// </summary>
        internal static string P_ALARM_042 {
            get {
                return ResourceManager.GetString("P_ALARM_042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH INKBOX 4.
        /// </summary>
        internal static string P_ALARM_043 {
            get {
                return ResourceManager.GetString("P_ALARM_043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH INKBOX 5.
        /// </summary>
        internal static string P_ALARM_044 {
            get {
                return ResourceManager.GetString("P_ALARM_044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH INKBOX 6.
        /// </summary>
        internal static string P_ALARM_045 {
            get {
                return ResourceManager.GetString("P_ALARM_045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH INKBOX 7.
        /// </summary>
        internal static string P_ALARM_046 {
            get {
                return ResourceManager.GetString("P_ALARM_046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH INKBOX 8.
        /// </summary>
        internal static string P_ALARM_047 {
            get {
                return ResourceManager.GetString("P_ALARM_047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK VACUUM DIFFERENCE, BAR 1.
        /// </summary>
        internal static string P_ALARM_048 {
            get {
                return ResourceManager.GetString("P_ALARM_048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK VACUUM DIFFERENCE, BAR 2.
        /// </summary>
        internal static string P_ALARM_049 {
            get {
                return ResourceManager.GetString("P_ALARM_049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK VACUUM DIFFERENCE, BAR 3.
        /// </summary>
        internal static string P_ALARM_050 {
            get {
                return ResourceManager.GetString("P_ALARM_050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK VACUUM DIFFERENCE, BAR 4.
        /// </summary>
        internal static string P_ALARM_051 {
            get {
                return ResourceManager.GetString("P_ALARM_051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK VACUUM DIFFERENCE, BAR 5.
        /// </summary>
        internal static string P_ALARM_052 {
            get {
                return ResourceManager.GetString("P_ALARM_052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK VACUUM DIFFERENCE, BAR 6.
        /// </summary>
        internal static string P_ALARM_053 {
            get {
                return ResourceManager.GetString("P_ALARM_053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK VACUUM DIFFERENCE, BAR 7.
        /// </summary>
        internal static string P_ALARM_054 {
            get {
                return ResourceManager.GetString("P_ALARM_054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK VACUUM DIFFERENCE, BAR 8.
        /// </summary>
        internal static string P_ALARM_055 {
            get {
                return ResourceManager.GetString("P_ALARM_055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK TEMPERATURE DIFFERENCE, BAR 1.
        /// </summary>
        internal static string P_ALARM_056 {
            get {
                return ResourceManager.GetString("P_ALARM_056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK TEMPERATURE DIFFERENCE, BAR 2.
        /// </summary>
        internal static string P_ALARM_057 {
            get {
                return ResourceManager.GetString("P_ALARM_057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK TEMPERATURE DIFFERENCE, BAR 3.
        /// </summary>
        internal static string P_ALARM_058 {
            get {
                return ResourceManager.GetString("P_ALARM_058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK TEMPERATURE DIFFERENCE, BAR 4.
        /// </summary>
        internal static string P_ALARM_059 {
            get {
                return ResourceManager.GetString("P_ALARM_059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK TEMPERATURE DIFFERENCE, BAR 5.
        /// </summary>
        internal static string P_ALARM_060 {
            get {
                return ResourceManager.GetString("P_ALARM_060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK TEMPERATURE DIFFERENCE, BAR 6.
        /// </summary>
        internal static string P_ALARM_061 {
            get {
                return ResourceManager.GetString("P_ALARM_061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK TEMPERATURE DIFFERENCE, BAR 7.
        /// </summary>
        internal static string P_ALARM_062 {
            get {
                return ResourceManager.GetString("P_ALARM_062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEADER TANK TEMPERATURE DIFFERENCE, BAR 8.
        /// </summary>
        internal static string P_ALARM_063 {
            get {
                return ResourceManager.GetString("P_ALARM_063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BAR 1 - MAIN TANK STIRRER THERMAL PROTECTION FAILURE.
        /// </summary>
        internal static string P_ALARM_064 {
            get {
                return ResourceManager.GetString("P_ALARM_064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BAR 2 - MAIN TANK STIRRER THERMAL PROTECTION FAILURE.
        /// </summary>
        internal static string P_ALARM_065 {
            get {
                return ResourceManager.GetString("P_ALARM_065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BAR 3 - MAIN TANK STIRRER THERMAL PROTECTION FAILURE.
        /// </summary>
        internal static string P_ALARM_066 {
            get {
                return ResourceManager.GetString("P_ALARM_066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BAR 4 - MAIN TANK STIRRER THERMAL PROTECTION FAILURE.
        /// </summary>
        internal static string P_ALARM_067 {
            get {
                return ResourceManager.GetString("P_ALARM_067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BAR 5 - MAIN TANK STIRRER THERMAL PROTECTION FAILURE.
        /// </summary>
        internal static string P_ALARM_068 {
            get {
                return ResourceManager.GetString("P_ALARM_068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BAR 6 - MAIN TANK STIRRER THERMAL PROTECTION FAILURE.
        /// </summary>
        internal static string P_ALARM_069 {
            get {
                return ResourceManager.GetString("P_ALARM_069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BAR 7 - MAIN TANK STIRRER THERMAL PROTECTION FAILURE.
        /// </summary>
        internal static string P_ALARM_070 {
            get {
                return ResourceManager.GetString("P_ALARM_070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BAR 8 - MAIN TANK STIRRER THERMAL PROTECTION FAILURE.
        /// </summary>
        internal static string P_ALARM_071 {
            get {
                return ResourceManager.GetString("P_ALARM_071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a START STIRRER IN BAR 1.
        /// </summary>
        internal static string P_ALARM_072 {
            get {
                return ResourceManager.GetString("P_ALARM_072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a START STIRRER IN BAR 2.
        /// </summary>
        internal static string P_ALARM_073 {
            get {
                return ResourceManager.GetString("P_ALARM_073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a START STIRRER IN BAR 3.
        /// </summary>
        internal static string P_ALARM_074 {
            get {
                return ResourceManager.GetString("P_ALARM_074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a START STIRRER IN BAR 4.
        /// </summary>
        internal static string P_ALARM_075 {
            get {
                return ResourceManager.GetString("P_ALARM_075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a START STIRRER IN BAR 5.
        /// </summary>
        internal static string P_ALARM_076 {
            get {
                return ResourceManager.GetString("P_ALARM_076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a START STIRRER IN BAR 6.
        /// </summary>
        internal static string P_ALARM_077 {
            get {
                return ResourceManager.GetString("P_ALARM_077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a START STIRRER IN BAR 7.
        /// </summary>
        internal static string P_ALARM_078 {
            get {
                return ResourceManager.GetString("P_ALARM_078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a START STIRRER IN BAR 8.
        /// </summary>
        internal static string P_ALARM_079 {
            get {
                return ResourceManager.GetString("P_ALARM_079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESERVOIR TEMPERATURE DIFFERENCE IN BAR 1.
        /// </summary>
        internal static string P_ALARM_080 {
            get {
                return ResourceManager.GetString("P_ALARM_080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESERVOIR TEMPERATURE DIFFERENCE IN BAR 2.
        /// </summary>
        internal static string P_ALARM_081 {
            get {
                return ResourceManager.GetString("P_ALARM_081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESERVOIR TEMPERATURE DIFFERENCE IN BAR 3.
        /// </summary>
        internal static string P_ALARM_082 {
            get {
                return ResourceManager.GetString("P_ALARM_082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESERVOIR TEMPERATURE DIFFERENCE IN BAR 4.
        /// </summary>
        internal static string P_ALARM_083 {
            get {
                return ResourceManager.GetString("P_ALARM_083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESERVOIR TEMPERATURE DIFFERENCE IN BAR 5.
        /// </summary>
        internal static string P_ALARM_084 {
            get {
                return ResourceManager.GetString("P_ALARM_084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESERVOIR TEMPERATURE DIFFERENCE IN BAR 6.
        /// </summary>
        internal static string P_ALARM_085 {
            get {
                return ResourceManager.GetString("P_ALARM_085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESERVOIR TEMPERATURE DIFFERENCE IN BAR 7.
        /// </summary>
        internal static string P_ALARM_086 {
            get {
                return ResourceManager.GetString("P_ALARM_086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESERVOIR TEMPERATURE DIFFERENCE IN BAR 8.
        /// </summary>
        internal static string P_ALARM_087 {
            get {
                return ResourceManager.GetString("P_ALARM_087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECIRCULATION STOPPED, BAR 1.
        /// </summary>
        internal static string P_ALARM_088 {
            get {
                return ResourceManager.GetString("P_ALARM_088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECIRCULATION STOPPED, BAR 2.
        /// </summary>
        internal static string P_ALARM_089 {
            get {
                return ResourceManager.GetString("P_ALARM_089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECIRCULATION STOPPED, BAR 3.
        /// </summary>
        internal static string P_ALARM_090 {
            get {
                return ResourceManager.GetString("P_ALARM_090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECIRCULATION STOPPED, BAR 4.
        /// </summary>
        internal static string P_ALARM_091 {
            get {
                return ResourceManager.GetString("P_ALARM_091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECIRCULATION STOPPED, BAR 5.
        /// </summary>
        internal static string P_ALARM_092 {
            get {
                return ResourceManager.GetString("P_ALARM_092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECIRCULATION STOPPED, BAR 6.
        /// </summary>
        internal static string P_ALARM_093 {
            get {
                return ResourceManager.GetString("P_ALARM_093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECIRCULATION STOPPED, BAR 7.
        /// </summary>
        internal static string P_ALARM_094 {
            get {
                return ResourceManager.GetString("P_ALARM_094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECIRCULATION STOPPED, BAR 8.
        /// </summary>
        internal static string P_ALARM_095 {
            get {
                return ResourceManager.GetString("P_ALARM_095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BROKEN TEMPERATURE SENSOR, RESERVOIR BAR 1.
        /// </summary>
        internal static string P_ALARM_096 {
            get {
                return ResourceManager.GetString("P_ALARM_096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BROKEN TEMPERATURE SENSOR, RESERVOIR BAR 2.
        /// </summary>
        internal static string P_ALARM_097 {
            get {
                return ResourceManager.GetString("P_ALARM_097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BROKEN TEMPERATURE SENSOR, RESERVOIR BAR 3.
        /// </summary>
        internal static string P_ALARM_098 {
            get {
                return ResourceManager.GetString("P_ALARM_098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BROKEN TEMPERATURE SENSOR, RESERVOIR BAR 4.
        /// </summary>
        internal static string P_ALARM_099 {
            get {
                return ResourceManager.GetString("P_ALARM_099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BROKEN TEMPERATURE SENSOR, RESERVOIR BAR 5.
        /// </summary>
        internal static string P_ALARM_100 {
            get {
                return ResourceManager.GetString("P_ALARM_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BROKEN TEMPERATURE SENSOR, RESERVOIR BAR 6.
        /// </summary>
        internal static string P_ALARM_101 {
            get {
                return ResourceManager.GetString("P_ALARM_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BROKEN TEMPERATURE SENSOR, RESERVOIR BAR 7.
        /// </summary>
        internal static string P_ALARM_102 {
            get {
                return ResourceManager.GetString("P_ALARM_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BROKEN TEMPERATURE SENSOR, RESERVOIR BAR 8.
        /// </summary>
        internal static string P_ALARM_103 {
            get {
                return ResourceManager.GetString("P_ALARM_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH TRANSPORT BELT MOTOR.
        /// </summary>
        internal static string P_ALARM_104 {
            get {
                return ResourceManager.GetString("P_ALARM_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO IMAGE LOADED TO PRINT.
        /// </summary>
        internal static string P_ALARM_105 {
            get {
                return ResourceManager.GetString("P_ALARM_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE BETWEEN PLC AND PC.
        /// </summary>
        internal static string P_ALARM_106 {
            get {
                return ResourceManager.GetString("P_ALARM_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a THICKNESS SENSOR ALARM.
        /// </summary>
        internal static string P_ALARM_107 {
            get {
                return ResourceManager.GetString("P_ALARM_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION FAILURE WITH PLC.
        /// </summary>
        internal static string P_ALARM_500 {
            get {
                return ResourceManager.GetString("P_ALARM_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLC IS STOPPED.
        /// </summary>
        internal static string P_ALARM_501 {
            get {
                return ResourceManager.GetString("P_ALARM_501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRINT SERVER NOT INITIALIZED.
        /// </summary>
        internal static string P_ALARM_502 {
            get {
                return ResourceManager.GetString("P_ALARM_502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RENDER SERVER DISCONNECTED.
        /// </summary>
        internal static string P_ALARM_503 {
            get {
                return ResourceManager.GetString("P_ALARM_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRINT SERVER NOT INITIALIZED - L2.
        /// </summary>
        internal static string P_ALARM_504 {
            get {
                return ResourceManager.GetString("P_ALARM_504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMMUNICATION ERROR CAMERA 1.
        /// </summary>
        internal static string P_ALARM_505 {
            get {
                return ResourceManager.GetString("P_ALARM_505", resourceCulture);
            }
        }
    }
}
