[Options]
;Este modo evita que se muestre por consola los resultados, sólo los guarda en el log
SilentMode=False
;tiempo en segundos entre las muestras (2 por defecto)
;TimeSpan=2
;Recoge información de los principales procesos además del total de cpu y de la memoria libre
ExtendedMode=true